export const ADMIN_HTML = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EarnSignal Console</title>
<style>:root{color-scheme:dark;--bg:#090d0b;--panel:#131a16;--line:#29352d;--ink:#edf5ef;--muted:#9bac9f;--green:#a9ec78;--amber:#f5bd68}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,sans-serif}.shell{width:min(1180px,calc(100% - 32px));margin:auto}header{display:flex;align-items:center;justify-content:space-between;padding:24px 0;border-bottom:1px solid var(--line)}h1{font-size:20px;margin:0}.status{color:var(--muted)}.auth{display:flex;gap:10px;padding:26px 0}.auth input{flex:1;min-width:0}input,button{font:inherit;padding:11px 13px;border:1px solid var(--line);border-radius:9px;background:var(--panel);color:var(--ink)}button{cursor:pointer;font-weight:700}button.primary{background:var(--green);border-color:var(--green);color:#10200e}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;padding-bottom:50px}.card{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:20px;min-height:220px}.card h2{font-size:15px;color:var(--green);margin:0 0 14px;text-transform:uppercase;letter-spacing:.08em}.card pre{white-space:pre-wrap;overflow-wrap:anywhere;margin:0;color:#cad7cd;font:12px/1.55 ui-monospace,monospace}.notice{color:var(--amber);padding-bottom:16px}.hidden{display:none}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style></head>
<body><div class="shell"><header><h1>EarnSignal / Operator Console</h1><span class="status" id="status">locked</span></header>
<section class="auth"><input id="token" type="password" autocomplete="off" placeholder="Admin bearer token（仅存 sessionStorage）"><button class="primary" id="unlock">Unlock</button></section>
<div class="notice">任何钱包签名、转账、合约部署或代币授权都不由此控制台执行。</div>
<section class="actions hidden" id="actions"><button id="refresh">Refresh reports</button><button id="discover">Run discovery</button><button id="generate">Generate daily report</button></section>
<main class="grid hidden" id="grid"><article class="card"><h2>Opportunity report</h2><pre id="opportunities"></pre></article><article class="card"><h2>Execution plan</h2><pre id="execution"></pre></article><article class="card"><h2>Revenue report</h2><pre id="revenue"></pre></article><article class="card"><h2>Improvement report</h2><pre id="improvement"></pre></article></main></div>
<script>const $=s=>document.querySelector(s);const tokenInput=$('#token');tokenInput.value=sessionStorage.getItem('earnsignalAdmin')||'';function headers(){return{Authorization:'Bearer '+tokenInput.value}}async function call(path,method='GET'){const response=await fetch(path,{method,headers:headers()});if(!response.ok)throw new Error(response.status+' '+await response.text());return response.json()}function show(report){$('#opportunities').textContent=JSON.stringify(report.opportunityReport,null,2);$('#execution').textContent=JSON.stringify(report.executionPlan,null,2);$('#revenue').textContent=JSON.stringify(report.revenueReport,null,2);$('#improvement').textContent=JSON.stringify(report.improvementReport,null,2);$('#actions').classList.remove('hidden');$('#grid').classList.remove('hidden');$('#status').textContent='connected · '+report.reportDate}async function load(){try{$('#status').textContent='loading…';show(await call('/admin/reports/daily'))}catch(error){$('#status').textContent='locked / '+error.message}}$('#unlock').onclick=()=>{sessionStorage.setItem('earnsignalAdmin',tokenInput.value);load()};$('#refresh').onclick=load;$('#discover').onclick=async()=>{await call('/admin/discovery/run','POST');await load()};$('#generate').onclick=async()=>show(await call('/admin/reports/generate','POST'));if(tokenInput.value)load();</script></body></html>`;

